typography_spectrum: 0.010885276598855853
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.41467107157222927
  lightness: 0.2793983737938106
  saturation: 0.487439192365855
  rhythmicContrast: 0.38131421408616006
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.934066653251648
analytics:
  google: null
  facebook: null
  twitter: null
name: Beijing
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Tag
purpose: []
